project:
  type: website
  output-dir: docs

website:
  title: "Nan Zhang"
  navbar:
    pinned: true
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - teaching.qmd

format:
  html:
    theme: sandstone
    linkcolor: "#0066ff"
    css: styles.css
    toc: false



