project:
  type: website
  output-dir: docs

website:
  title: "Nan Zhang"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd

format:
  html:
    theme: sandstone
    linkcolor: "#0066ff"
    css: styles.css
    toc: true



