project:
  type: website
  output-dir: docs

website:
  title: "Nan Zhang"
  
  navbar:
    pinned: true
    search: false
    left:
      
      - text: "Home"
        href: index.qmd

      - text: "Research" 
        href: research.qmd
        
      - text: "Teaching"
        href: teaching.qmd

format:
  html:
    page-layout: full
    theme: sandstone
    linkcolor: "#0066ff"
    css: styles.css
    toc: true



