---
title: "Teaching"
---

---


### Political Sociology Seminar: Experiments on Voting

Political participation represents an enduring puzzle for political scientists: given that an individual vote is rarely decisive, why do people bother to go to the polls? 

In this seminar, we will address this question via some of the latest experimental research on voting and turnout. The goal is provide students with both an overview of recent evidence on voting behavior, as well as an applied introduction to state-of-the-art methods for drawing inferences from experimental and observational data.

The link to the syllabus is [here](https://nanzhang-polisci.github.io/Turnout_FSS26)

---

### Comparative Politics Tutorial: Causal Inference

This course will teach students how to analyze research questions in Comparative Politics through the application of causal inference methods. 

We will begin by asking what it means for X to cause Y using the framework of potential outcomes. We will then look at some of the most popular research designs in causal analysis including experiments, regression discontinuity designs, difference-in-differences / two-way fixed effects, and instrumental variables.

Students will learn to apply these methods to real data in R.

The overarching goal is to provide students with the foundation to perform their own analyses (e.g. for their BA theses) by transferring the acquired skills to their research interests.

The link to the syllabus is [here](https://nanzhang-polisci.github.io/QMCP_FSS26.html)

---

### BA Thesis Colloquium in International Relations

This course involves support for writing a BA thesis in political science. 

Students will need to design and carry a research strategy that includes (i) identifying an original contribution to a body of literature, (ii) finding or generating appropriate data, and (iii) conducting a rigorous data analysis. 

This colloquium is designed to help students progress along each of these steps by providing periodic feedback from the instructor.

The link to the syllabus is [here](https://nanzhang-polisci.github.io/BA_Colloq.html).